<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * Reports are generated by Staff members → references staffs.staffID
     */
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            $table->id('reportID');
            $table->unsignedBigInteger('generatedBy'); // staff who generated the report
            $table->string('title');
            $table->enum('report_type', ['booking', 'job_record', 'feedback', 'revenue']);
            $table->date('date_from')->nullable();
            $table->date('date_to')->nullable();
            $table->longText('content')->nullable();
            $table->timestamps();

            // FK → staffs (reports are generated by staff/admin)
            $table->foreign('generatedBy')
                  ->references('staffID')->on('staffs')
                  ->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
