<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'phone',
        'address',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /**
     * Check if user is staff.
     */
    public function isStaff(): bool
    {
        return $this->role === 'staff';
    }

    /**
     * Check if user is customer.
     */
    public function isCustomer(): bool
    {
        return $this->role === 'customer';
    }

    /**
     * Get bookings made by this customer.
     */
    public function bookings()
    {
        return $this->hasMany(Booking::class, 'customer_id');
    }

    /**
     * Get bookings assigned to this staff.
     */
    public function assignedBookings()
    {
        return $this->hasMany(Booking::class, 'staff_id');
    }

    /**
     * Get job records handled by this staff.
     */
    public function jobRecords()
    {
        return $this->hasMany(JobRecord::class, 'staff_id');
    }

    /**
     * Get feedbacks given by this customer.
     */
    public function feedbacks()
    {
        return $this->hasMany(Feedback::class, 'customer_id');
    }

    /**
     * Get reports generated by this staff.
     */
    public function reports()
    {
        return $this->hasMany(Report::class, 'generated_by');
    }
}
